name: test
on:
  - push
  - pull_request
  - workflow_call

jobs:
  test_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  test_windows:
    if: ${{ !inputs.disable-windows }}
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  lint:
    uses: adonisjs/.github/.github/workflows/lint.yml@next

  typecheck:
    uses: adonisjs/.github/.github/workflows/typecheck.yml@next
